### ISSUE TITLE
Erreur de comparaison entre 38.0.4-3 et 38.0.4-3~deb12u1

### ISSUE THREAD

**Issue by tarraschk** [Cyberwatch/software-version#25]
Salut,

pour info la manière dont on utilise le `~` peut mener à des résultats incorrects dans le calcul des comparaisons.

Typiquement, pour python3-cryptography, on a :

![image](https://github.com/Cyberwatch/software-version/assets/2057917/e429ecd4-ead9-4a30-b160-b1418a3f6ab0)

Et software-version considère que la version 38.0.4-3 est plus petite que 38.0.4-3~deb12u1.

Cela enfreint la règle suivante sur Debian :

https://www.debian.org/doc/manuals/debmake-doc/ch05.en.html#name-version

Avec la partie suivante :

```
0.0 < 0.5 < 0.10 < 0.99 < 1 < 1.0~rc1 < 1.0 < 1.0+b1 < 1.0+nmu1 < 1.1 < 2.0
```

Exemple :

```ruby
SoftwareVersion::Version.new('38.0.4-3~deb12u1') < SoftwareVersion::Version.new('38.0.4-3')
=> false
```

Alors qu'on devrait avoir `true`.

Cas pour reproduire :

```
docker run -it debian:12 /bin/bash
apt update
apt install python3-cryptography=38.0.4-3
apt install python3-cryptography=38.0.4-3~deb12u1
# ...
# dpkg: warning: downgrading python3-cryptography from 38.0.4-3 to 38.0.4-3~deb12u1
# ...
```

**Comment by fmang** [comment]
Actuellement software-version traite les tildes comme un séparateur neutre, et ce qui suit fait donc monter la version. Pour lister différents cas dans la nature :

1. grub2.x86_64 2.06~rc1-1.fc33
2. libaspell-dev 0.60.7~20110707-4
3. libclamav9 0.103.5+dfsg-1~20.04.1
4. bind9 1:9.7.3.dfsg-1~squeeze1
5. golang-x-text.x86_64 0.3.7-3.fc35~bootstrap

Le premier est un cas clair de pré-version qu’on sait gérer grâce au préfixe *rc*. Les autres le sont moins. Le dernier n’est clairement pas une préversion, mais n’est pas non plus une mise à jour bien qu’on considèrera la verion supérieure à cause du suffixe. Le cas de libaspell est bien une pré-release si je me fie au [changelog de aspell](http://aspell.net/man-html/ChangeLog.html#Changes-from-0_002e60_002e6_002e1-to-0_002e60_002e7-_0028July-29_002c-2019_0029), et je suppose que le cas bind9 aussi d’après le guide que tu cites. Le cas clamav ressemble à du Ubuntu, donc devrait aussi suivre la nomenclature Debian.

Je n’observe pas de cas apparent où le tilde est suivi d’une mise à jour, donc on pourrait juger que tilde préfixe une préversion. Ce ne serait pas un changement difficile.

**Comment by fmang** [comment]
J’ai ouvert une MR pour considérer le tilde comme une pré-version, ce qui nous rapprochera du comportement de Debian.

J’étais tenté d’éliminer les mots de plusieurs lettres dans les versions car ils ne sont pas comparables, puis de supprimer les séparateurs en fin de version afin que `1~bootstrap` soit normalisé en `1~` puis `1`. Cependant, même si les mots ne sont pas comparables, il ont une valeur sémantique. `1.el7` n’est pas la même chose que `1.7`. Avant de sortir la magie noire pour ce cas particulier, je préfère attendre d’avoir plus de recul.

Merci pour la remontée du problème.
